
export const GET_USERS = 'GET_USERS'
export const ADD_USER = 'ADD_USER'
export const LOGIN = 'LOGIN'

export const GET_MEETUPS = 'GET_MEETUPS'
export const ADD_MEETUP = 'ADD_MEETUP'
export const UPDATE_MEETUP = 'UPDATE_MEETUP'
export const GET_CATEGORIES = 'GET_CATEGORIES'
// export const LOGIN_USER = 'LOGIN_USER'
export const AUTHENTICATED = 'AUTHENTICATED'
export const LOGIN_AUTHENTICATED = 'LOGIN_AUTHENTICATED'
export const DEFAULT_MAP = 'DEFAULT_MAP'
export const GET_MEETUP_COORDINATES = 'GET_MEETUP_COORDINATES'
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR'
export const SAVE_USER = 'SAVE_USER'
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE'

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'
